- apps/pudl/src/App.vue
- apps/pudl/src/main.css
- apps/pudl/src/router/index.ts
- apps/pudl/src/store/index.ts
- apps/pudl/tailwind.config.js
- packages/components/package.json
- packages/components/src/components/login/LoggedIn.vue
- packages/components/src/components/login/SignIn.vue
- packages/components/src/composables/use-login.ts
- packages/components/src/pages/Logout.vue
- packages/components/src/pages/OAuth.vue
- packages/components/vite.config.ts
- tailwind.config.js
> feat: Add login requirement to PUDL UI

- .github/workflows/stage-apps.yaml
- .github/workflows/stage-services.yaml
> feat: Add sign library workflow strategy

- apps/lcr/src/pages/ComputerPage.vue
- apps/lcr/src/store/lcr.ts
- apps/lcr/src/types/pagedCopActiveComputers-bk.ts
> feat: Add ability to save notes to a computer

- apps/lcr/src/router/index.ts
- apps/lcr/vite.config.ts
> chore: Add VITE_BASE_PATH to better support deployments/builds

- apps/lcr/src/pages/Home.vue
- apps/lcr/src/pages/UserPage.vue
- apps/lcr/src/types/pagedMaximoUsers.ts
> feat: Add supervisor name to maximo user info pages

- apps/lcr/src/App.vue
- apps/lcr/src/components/pager/Pager.vue
- apps/lcr/src/main.ts
- apps/lcr/src/pages/LcrSchedule.vue
- apps/lcr/src/router/index.ts
- apps/lcr/src/store/lcr.ts
- apps/lcr/src/types/pagedPbotLcrSchedule.ts
- package.json
- pnpm-lock.yaml
> feat: Add paged LCR Schedule page and make it cache to local storage

- apps/lcr/src/components/pager/Pager.vue
- apps/lcr/src/pages/ComputerPage.vue
- apps/lcr/src/pages/Home.vue
- apps/lcr/src/pages/LcrSchedule.vue
- apps/lcr/src/store/lcr.ts
> chore: cleanup

- apps/lcr/src/pages/ComputerPage.vue
> chore: Quick fix on new links

- apps/lcr/src/pages/ComputerPage.vue
> chore: get link to work

- apps/lcr/src/App.vue
- apps/lcr/src/pages/ActiveComputers.vue
- apps/lcr/src/pages/UserPage.vue
- apps/lcr/src/router/index.ts
- apps/lcr/src/store/lcr.ts
- apps/lcr/src/types/pagedCopActiveComputers.ts
> feat: Add paginated page for copActiveComputers and cleanup some types

- apps/lcr/src/pages/ActiveComputers.vue
> feat: Fix search fields on copActiveComputers page

- apps/lcr/src/components/replacementStatus/ReplacementStatus.vue
- apps/lcr/src/pages/ActiveComputers.vue
- apps/lcr/src/pages/ComputerPage.vue
- apps/lcr/src/pages/LcrSchedule.vue
- apps/lcr/src/store/lcr.ts
- apps/lcr/src/types/pagedCopActiveComputers.ts
- apps/lcr/src/types/pagedPbotLcrSchedule.ts
- apps/lcr/vite.config.ts
> feat: Add status dropdown to computers in app and allow it to update

- apps/lcr/src/pages/Home.vue
> feat: Add clear button for search fields on user page

- apps/lcr/src/pages/ComputerPage.vue
> chore: Fix alignment on certain fields

- apps/lcr/src/pages/ComputerPage.vue
> chore: Fix widths when adjusting toggle panel

- apps/lcr/src/store/lcr.ts
> feat: Add retired status to computers

- apps/lcr/src/pages/ComputerPage.vue
> feat: Make computer page layout responsive

- apps/lcr/src/components/SortIndicator/SortIndicator.vue
- apps/lcr/src/pages/Home.vue
- apps/lcr/src/store/lcr.ts
- apps/lcr/src/types/pagedMaximoUsers.ts
> feat: allow sorting of fields on computer page

- apps/lcr/src/pages/ActiveComputers.vue
> feat: Parameterize report URLs into ENV variables

- apps/support/tailwind.config.js
- services/support/src/pages/index.md
- services/support/src/pages/requests.md
- services/support/src/pages/team.md
Added Service Now link.
ref: sos-284
> Fix: Update requests.md

- apps/lcr/src/pages/Home.vue
> Add feat: Center the home page table.

- services/support/scripts/build.mjs
> fix: Make directories for pages before copying

- apps/support/src/router/index.ts
> fix: Route to login if there is no access token

- apps/support/src/App.vue
- packages/components/src/components/login/SignIn.vue
- packages/components/src/composables/use-login.ts
- packages/components/src/pages/Login.vue
- packages/components/src/pages/OAuth.vue
> fix: Route to original destination after login

- apps/support/src/router/index.ts
- packages/components/src/components/login/SignIn.vue
- packages/components/src/composables/use-login.ts
- packages/components/src/pages/Login.vue
- packages/components/src/pages/Logout.vue
Use stored route on login page
Update typings
Add redirecting on logout page
ref: VERT-827
> fix(support): Store route before redirecting

- services/support/src/pages/index.md
- services/support/src/pages/requests.md
- services/support/src/pages/team.md
Service Now featured at top of requests.md
Project Support button moved to top of section on requests.md
Minor content updates on requests.md and index.md
ref: sos-284
> fix: Content and layout updates

- services/support/src/pages/requests.md
Also changes wording and fixes typo
ref: SOS-284
> feat(support): Create message box on request page

- .github/workflows/push-tag.yaml
- .github/workflows/release-apps.yaml
- .github/workflows/release-services.yaml
> feat: Add workflows to release support site

- services/support/src/pages/team.md
Updated sumbmit to submit.
ref: sos-288
> fix: Typo on team.md

- apps/pudl/src/pages/schema.vue
- apps/pudl/src/pages/table.vue
- apps/pudl/src/pages/zone.vue
- apps/pudl/src/pages/zones.vue
- apps/pudl/src/store/index.ts
> feat: Order PUDL Objects by Name in the lists

- services/sign/src/types.ts
> fix: Add triangle to allowed sign shapes

- apps/sign-library/src/pages/Edit.vue
Moves code ref value out from computed sign value
ref: SOS-671
> feat: Uppercase sign code inputs

- apps/sign-library/src/App.vue
- apps/sign-library/src/pages/Edit.vue
- apps/sign-library/src/pages/Home.vue
- packages/components/src/components/field/Entry.vue
- packages/components/src/components/login/LoggedIn.vue
- packages/components/src/components/pager/Pager.vue
Adds alt field to images in specific app and components Adds for to field entry component
Adds aria-label to complex input fields
ref: SOS-492
> feat(signlib): Address accessibility issues

- apps/admin/package.json
- apps/pudl/package.json
- apps/sign-library/package.json
- apps/sign-library/src/pages/Home.vue
- apps/support/package.json
- package.json
- packages/components/package.json
- pnpm-lock.yaml
> feat(signlib): Add attribute to search listings

- apps/pudl/src/pages/home.vue
Incorporate suggested changes
Fix typo(s)
ref: PUDL-458
> refactor(pudl): Update homepage text

- apps/pudl/src/pages/home.vue
> fix(pudl): Typo on homepage

- apps/sign-library/src/pages/Edit.vue
- packages/components/src/elements/input/Checkbox.vue
- packages/components/src/elements/input/Checkboxes.vue
> feat: Add required validation support for checkboxes

- packages/components/src/elements/input/Checkboxes.vue
> fix(components): Reverse logic on invalid checkboxes

- services/support/src/pages/requests.md
> chore: update text in GIS and Training sections

- .github/workflows/stage-apps.yaml
- apps/admin/package.json
- apps/admin/src/App.vue
- apps/admin/src/components/application/Form.vue
- apps/admin/src/components/rule/Form.vue
- apps/admin/src/pages/Application.vue
- apps/admin/src/pages/Rule.vue
- apps/admin/src/store/application.ts
- apps/admin/src/store/auth.ts
- apps/admin/src/store/user.ts
- apps/pudl/package.json
- apps/pudl/src/App.vue
- apps/pudl/src/store/index.ts
- apps/pudl/src/store/rules.ts
- apps/sign-library/src/App.vue
- apps/sign-library/src/store/index.ts
- apps/support/package.json
- apps/support/src/App.vue
- apps/support/src/main.ts
- apps/support/src/pages/Page.vue
- apps/support/src/router/index.ts
- apps/support/src/store.ts
- packages/authorization/src/composable.ts
- packages/authorization/src/index.ts
- packages/authorization/src/store.ts
- packages/authorization/src/types.ts
- packages/authorization/src/utils.ts
Remove MSAL dependency and use custom authentication components
ref: VERT-917
> refactor: Authorization components

- .github/workflows/stage-apps.yaml
- apps/bus-reservation/vite.config.ts
> fix: Add base url to vite config

- packages/cosmos/package.json
- packages/cosmos/src/index.ts
- packages/cosmos/src/repository.ts
- packages/cosmos/tsconfig.build.json
- packages/graphql/src/types/geojson.ts
- packages/graphql/src/types/index.ts
- pnpm-lock.yaml
- services/reservation/nodemon.json
- services/reservation/package.json
- services/reservation/src/base/types.ts
- services/reservation/src/hotel/index.ts
- services/reservation/src/hotel/schema.ts
- services/reservation/src/hotel/types.ts
- services/reservation/src/index.ts
- services/reservation/src/reservation/schema.ts
- services/reservation/src/reservation/types.ts
- services/reservation/src/server.ts
- services/reservation/src/zone/index.ts
- services/reservation/src/zone/schema.ts
- services/reservation/src/zone/types.ts
- services/reservation/tsconfig.build.json
> feat: Add initial reservation service

- apps/bus-reservation/src/App.vue
- apps/bus-reservation/src/pages/home.vue
- apps/bus-reservation/src/pages/hotels/list.vue
- apps/bus-reservation/src/pages/reservations/list.vue
- apps/bus-reservation/src/router/index.ts
- apps/bus-reservation/src/store/index.ts
- services/reservation/src/base/types.ts
- services/reservation/src/hotel/schema.ts
- services/reservation/src/hotel/types.ts
- services/reservation/src/index.ts
- services/reservation/src/reservation/index.ts
- services/reservation/src/reservation/schema.ts
- services/reservation/src/rules.ts
- services/reservation/src/server.ts
> feat: Add rules to bus reservation app and service

- apps/bus-reservation/src/pages/hotels/addedit.vue
- apps/bus-reservation/src/pages/hotels/list.vue
- apps/bus-reservation/src/pages/hotels/view.vue
- apps/bus-reservation/src/store/index.ts
- services/reservation/src/hotel/schema.ts
- services/reservation/src/hotel/types.ts
- services/reservation/src/reservation/schema.ts
> feat: Hotel admin backend calls

- apps/bus-reservation/src/pages/reservations/addedit.vue
> feat: filter spots based on start and end date selected

- .vscode/settings.json
- apps/bus-reservation/src/pages/hotels/list.vue
- apps/bus-reservation/src/pages/reservations/list.vue
- services/reservation/src/reservation/schema.ts
> feat: Add validation when filtering dates for reservations

- apps/sign-library/src/pages/Home.vue
Check before navigating to page 1 if already on page 1
ref: VERT-988
> fix: de-duplicate navigation to page 1

- packages/components/src/elements/input/Checkboxes.vue
> fix: Reactive required logic for multiple checkboxes

- services/reservation/src/reservation/schema.ts
> fix: filter for active reservations when checking for existing ones

- services/sign/src/server.ts
> chore: Add new user to sign library

- apps/amanda/package.json
> fix: Add missing build dependencies

- apps/amanda/vite.config.ts
> fix: path to app when deployed

- services/sign/src/sign/types.ts
Some old data stil ahs null values and is not being returned
ref: ESS-676
> refactor: Allow null sign sizes

- apps/amanda/src/pages/Backoffice.vue
> feat: add new PBOT Amanda layers

- apps/amanda/public/amanda-gis.js
- apps/amanda/src/pages/CitizenPortal.vue
> feat: Handle backoffice selection of multiple layers

- apps/amanda/public/amanda-gis.js
> fix: Add queries to promises when selecting

- apps/sign-library/src/pages/Home.vue
> fix: escape special characters before using regex

- apps/amanda/package.json
- apps/amanda/public/amanda-gis.js
- apps/amanda/src/App.vue
- apps/amanda/src/components/Map.vue
- apps/amanda/src/pages/Backoffice.vue
- apps/amanda/src/pages/CitizenPortal.vue
- apps/amanda/src/router/index.ts
> feat: Add address searching to AMANDA map

- .github/workflows/push-tag.yaml
- .github/workflows/stage-apps.yaml
- packages/components/src/composables/use-graphql.ts
> feat: Use URL in GraphQL options for AMANDA map

- .github/workflows/stage-apps.yaml
> fix: Mode for env file in staging

- apps/amanda/src/components/Map.vue
> fix: Use SpatialReference constructor

- apps/amanda/public/amanda-gis.js
> fix: Project circle to lon/lat before searching

- apps/amanda/public/amanda-gis.js
> fix: Load projections before using

- services/sign/src/sign/schema.ts
Set on image file uploads. Hope is to help browser caching issues.
ref: INC0067456
> feat: Set content-type and cache-control headers

- apps/sign-library/src/components/sign/Form.vue
> feat: Replace by workorder do not required a sign

- apps/amanda/src/components/Map.vue
- apps/amanda/src/pages/Backoffice.vue
> fix: update Map component to add layers before emitting map

- apps/amanda/public/amanda-gis.js
getAllLaters will wait until known number of layers are available through the amanda layers
ref: INC0078309
> fix: update layer retrieval to use getAllLayers method

- apps/amanda/public/amanda-gis.js
> fix: improve layer readiness check by excluding amanda graphic layers
